#!/bin/sh

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE $APP_BACKEND_USER LOGIN PASSWORD '$APP_BACKEND_PASSWORD';

  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $APP_BACKEND_USER;

  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $APP_BACKEND_USER;
EOSQL
